spring:
#mysql数据库连接配置
  datasource:
    url: jdbc:mysql://10.10.10.10:3306/kehaoduo-sit?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
