spring:
  profiles:
    active: common, common_@profileActive@, salarybill_dao, salarybill_dao_@profileActive@

#日志
logging:
  level:
    com.htcs: debug
  path: c:/webapp/logs/system
server:
  context-path: /salarybill
  port: 8082
  session:
    timeout: 1800


# 恒天公众号
wechat:
  mp:
    appId: wx1b0723ab8a95d54a
    secret: 6036488697434073fe91ddee23f7ab67
    token: 2jo3qu4nt98234ut89
    aesKey:
#工资条企业微信应用
enterprise:
  corpid: wwe4faf154efbc8119
  agentId: 1000031
  corpsecret: omOqopOrRKkrHHOCIAw8jaN03f_OKdkbCKWVwCTXgiU